force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <label>Candidate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candiates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/Background_Checked__c.field-meta.xml
<CustomField>
    <fullName>Background_Checked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Pre-employment background check is done.</description>
    <label>Background Checked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/RunBackgroundCheck.cls
public with sharing class RunBackgroundCheck {
    @Future(callout=true)
    public static void callOutToBlockchain(String id, String ssn) {
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        
        //id param needs to prepend with ns, such as 'resource:org.blockchain.mynetwork.Individual#123-45-6789'
        request.setEndpoint('http://50.23.5.251:31090/api/queries/selectRecords?govIdParam=resource%3Aorg.blockchain.mynetwork.Individual%23'+ssn);
        request.setMethod('GET');
        HttpResponse response = http.send(request);
        
        // If the request is successful, parse the JSON response.
        if (response.getStatusCode() == 200) {
            List<Object> results = (List<Object>) JSON.deserializeUntyped(response.getBody());
            
            Candidate__c candidate = [Select Id  from Candidate__c where Id=:id limit 1];
            if (results.size() > 0) {
                Map<String, Object> result = (Map<String, Object>) results.get(0);
                String description = (String) result.get('description');
                candidate.Description__c = description;
                candidate.Background_Checked__c = false;
            } else {
                candidate.Background_Checked__c = true;
            }
            update candidate;
        }
    }
}